### PR TITLE
Problem with floats in /api

### PR DESCRIPTION
**Pull request by NV**
screen shot 2013-09-27 at 12 55 31 pm

For example, on http://montagejs.org/api/AbstractControl.html

### CODE REVIEW

**Comment by NV** [comment]
With the pull request applied:

screen shot 2013-10-03 at 2 22 05 am

To see updated the following must be run first:

```
_build ➤ npm install
_build ➤ ./build.js
```

I’m not sure about striped rows and `font-weight: bold` for headers. It inherited from the table styles.

**Comment by simurai** [comment]
Looks good. Also works when resizing the browser.

**Pull request merged**
