### PR TITLE
Add support for generating Digit JSDoc

### PR DESCRIPTION
**Pull request by francoisfrisch**

### CODE REVIEW

**Comment by francoisfrisch** [comment]
build.js worked for me

**Comment by Stuk** [comment]
Running `_build/build.js` works, but only generates Montage docs, no Digit docs...?

**Comment by francoisfrisch** [comment]
not yet

**Comment by Stuk** [comment]
How can I test that it's working properly for other packages?

**Comment by francoisfrisch** [comment]
you can do `./jsdoc.js digit npm-link`

**Comment by Stuk** [comment]
Afraid that only seems to link digit into `_build/jsdoc/lib/node_modules/digit`. It doesn't generate anything.

**Comment by francoisfrisch** [comment]
should be good now

**Comment by Stuk** [comment]
Still does not work for me

``` bash
$ ./jsdoc.js digit npm-link
npm link digit
npm http GET https://registry.npmjs.org/digit
#...
digit@0.3.2 lib/node_modules/digit
├── matte@0.1.4 (native@0.1.3)
└── montage@0.13.7 (frb@0.2.15, collections@0.2.1, mousse@0.1.4, htmlparser2@3.0.5)
$ git status
# On branch other-packages
# Your branch is ahead of 'origin/other-packages' by 16 commits.
#   (use "git push" to publish your local commits)
#
nothing to commit, working directory clean
```

**Comment by francoisfrisch** [comment]
this should be the good one :$

**Comment by Stuk** [comment]
Generating now works. Some problems:
- "Source" links point to montage repo
- "Generated from" link points to montage repo
- There's a Tutorial README, which looks like it comes from JSDoc
- Clicking on the title in Badge, Image, ListItem, Text, Title or VideoControl links to `api/digit/___.html`, where the number of `_`s is correlated with the position in that list(?!).

**Comment by aadsm** [comment]
The `Source :` link points to the montage repository

**Comment by Stuk** [comment]
Pointed that out in my comment :)

**Comment by aadsm** [comment]
oops, missed it :) the funny part is that I actually read through to make sure it wasn't mentioned already :D

**Comment by francoisfrisch** [comment]
@Stuk 

> Clicking on the title in Badge, Image, ListItem, Text, Title or VideoControl links to api/digit/___.html, where the number of _s is correlated with the position in that list(?!).

Can't reproduce this which title are you talking about?

**Comment by Stuk** [comment]
See "status bar":
screen shot 2013-11-13 at 2 05 54 pm
Edit: I'm hovering over the `"ui/title.reel".` link

**Comment by francoisfrisch** [comment]
Oh I see this is due to some problems in the JSDoc tagging in digit

**Pull request merged**
