### PR TITLE
Yellow vs Grey code

### PR DESCRIPTION
**Pull request by simurai**
:warning: More opinions needed before merging :warning: 

Replaces the yellowish background of `inline code` and

```
Code Blocks
```

with a light grey background:

grey

Current (yellow) vs new (grey):

compare
## Opinions

@segphault: Main voice behind removing yellow

@mikokim: Would like `inline code` without the border/background and only monospaced font. It's for easier scanning of the text.

@simurai Likes the yellow since it matches the syntax highlighting. Also makes it easier to see what is code and what is text.

Anyone more preferences?

### CODE REVIEW

**Comment by kriskowal** [comment]
Gray. I wouldn’t mind removing the bg and border of inline code.

**Comment by aadsm** [comment]
I prefer the gray background too, can we see how it looks like without the border?

**Comment by simurai** [comment]
Here the no border version for inline code. Basically just different font and color:

no-border

**Comment by kriskowal** [comment]
:shipit:

**Comment by Stuk** [comment]
I like the grey :+1:

**Comment by simurai** [comment]
Ok, I think there is enough consensus to merge this.

**Pull request merged**
