### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by simurai**
This checks a `404` against a list of redirects and if there is a match it forwards to the new location. That way we could get rid of all the other redirect html files that start cluttering up everywhere.

Also see benefits in #34. Might also solve #62.
- In this PR I just added 3 tests to the list, if the script is ok, I'll add the real ones and remove the html files.

### CODE REVIEW

**Comment by NV** [comment]
Nitpick. I’d use a dictionary for the routes. It’s less code and it has a constant look up time (which doesn’t matter for 3 urls).

``` javascript
var redirects = {
  '/test.html': '/docs/montagejs-setup.html',
  '/docs/test.html': '/docs/draw-cycle.html',
  '/test': '/docs/frb.html'
};

if (redirects.hasOwnProperty(path)) {
    window.location = redirects[path];
}
```

**Comment by simurai** [comment]
@NV You mean then I don't need that for loop and stuff? Ohh.. thanks. Ya, that looks a lot slicker.

Changed it.. good like that?

**Comment by NV** [comment]
Right, loop isn’t needed.

:shipit:

**Comment by NV** [comment]
I’m not entirely sure I’m the right person to decide whether merge it or not but since it looks harmless I’m merging it.

**Comment by simurai** [comment]
Seems to work fine. Example: http://montagejs.org/docs/test.html

Ok, I'll make another PR with all the actual redirects.

**Pull request merged**
