### PR TITLE
On /api, add links to source code on GitHub

### PR DESCRIPTION
**Pull request by NV**
source-links

### CODE REVIEW

**Comment by kriskowal** [comment]
Awesome.

**Comment by Stuk** [comment]
LGTM. I have it merged and generated locally if there are no objections.

**Comment by Stuk** [comment]
The api needs to be built locally, committed and pushed as well.

**Comment by NV** [comment]
@Stuk, right, thanks for reminding. It’s here montagejs/montagejs.org#48

**Pull request merged**
