### PR TITLE
Make JSDoc output more compact

### PR DESCRIPTION
**Pull request by kriskowal**
- Source links are consolidated into the same line as the doclet name,
  with the font size reduced.  The file name is rendered in the page
  title, but only the line number for each individual method or
  property.
- Property and method names always appear flush with the left margin.
  Attributes follow the name and signature, but precede the source link.
- Return description and type are consolidated into a single line if
  possible.

### CODE REVIEW

**Comment by Stuk** [comment]
Example images:
screen shot 2013-11-19 at 1 51 15 pm
screen shot 2013-11-19 at 1 51 54 pm

**Comment by Stuk** [comment]
I'd prefer it if the source links were just "source", instead of the filename and L##. The filename is pretty obvious that it links to the source, but I don't think "L" is.

**Comment by Stuk** [comment]
The consolidated "Returns" looks good on the Localizer page, which is the only example I could find.

**Comment by Stuk** [comment]
I took the liberty of rebasing this on top of the latest gh-pages

**Comment by kriskowal** [comment]
I’m fine with changing the source link to a dagger even. It should not distract. I would be fine with `source`, even or `line&nbsp;` + line number as the prefix.

**Comment by NV** [comment]
I’d use `line&nbsp; +` line number. I think, it could be a slightly lighter shade than the rest of the links.

P.S. Why do we display curly braces for return type? Seems redundant to me.

**Comment by Stuk** [comment]
source

screen shot 2013-11-19 at 4 37 12 pm
screen shot 2013-11-19 at 4 37 25 pm

line ##

screen shot 2013-11-19 at 4 40 58 pm
screen shot 2013-11-19 at 4 41 07 pm

**Comment by kriskowal** [comment]
You can make the call @stuk. Looks fine either way to me. I’m just glad to have it consolidated so it doesn’t consume 100px of vertical all by itself.

**Pull request merged**
