### PR TITLE
Post: What is in a flick

### PR DESCRIPTION
**Pull request by simurai**
Demo is included in the `blog/2013-11-08-what-is-in-a-flick` directory.

### CODE REVIEW

**Comment by simurai** [comment]
Ahhm.. did this get mopped right? 1100 files seems quite a lot. All components are added even if it only uses a Slider, is that normal?

In order to keep the site as light weight as possible, should we move this demo into another repo and link to that?

**Comment by mikokim** [comment]
Afonso needs to review before we go live. 

Typed with unquestionable inaccuracy on tiny keyboard.

**Comment by aadsm** [comment]
Oh yes, I'm going to remove all the unnecessary files :) we only need the bundle and a few css files.

**Comment by aadsm** [comment]
I created a PR with the changes: https://github.com/montagejs/montagejs.org/pull/61

**Pull request merged**
